### ISSUE TITLE
Fvwm-mode.el comment highlighting

### ISSUE THREAD

**Issue by parszab** [theBlackDragon/fvwm-mode#3]
Hi,
I was happy to find the emacs mode to edit fvwm config files. However it seems that commented lines are not highlighted correctly, not sure if it's an easy fix, it was not obvious to me with the many regexes.

![0x280013e](https://user-images.githubusercontent.com/15095671/206869120-ad15adc5-ad64-4479-ba43-91c7891ab2e3.png)

**Comment by theBlackDragon** [comment]
Having trouble reproducing this.

What version of Emacs are you on and would it be possible for you to share your config file somehow?

**Comment by parszab** [comment]
Thx for getting back. I was using Doom-emacs when having this issue. Since than I created my own config, and with it commenting works. I have to disable company mode though, otherwise it becomes very slow, e.g. search with swiper. Anyways, feel free the close the issue.

**Comment by theBlackDragon** [comment]
Alright, thanks for the feedback! Sounds like it might've been a conflict with some setting Doom changes.
